# Generated by Django 4.1.4 on 2023-05-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bouteille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PLASTIQUE1L', 'Option 1'), ('PLASTIQUE1.5L', 'Option 2'), ('PLASTIQUE0.5L', 'Option 3'), ('PLASTIQUE2L', 'Option 4'), ('CANETTE', 'Option 5')], default='PLASTIQUE1L', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='recompense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=100)),
                ('recompenses', models.ManyToManyField(to='webapp.recompense')),
            ],
        ),
        migrations.CreateModel(
            name='rvm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=30)),
                ('quantite', models.IntegerField(default=0)),
                ('quantiteMax', models.IntegerField(default=0)),
                ('bouteilles', models.ManyToManyField(to='webapp.bouteille')),
            ],
        ),
    ]
