# Generated by Django 4.2.1 on 2023-05-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_recompense_description_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recompense',
            name='description',
            field=models.CharField(default='ENTRER LA DESCRIPTION', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='SIMPLE_USER', max_length=100),
        ),
    ]
