# Generated by Django 4.2.1 on 2023-05-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_recompense_description_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvm',
            name='bouteilles',
            field=models.ManyToManyField(null=True, to='webapp.bouteille'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recompenses',
            field=models.ManyToManyField(null=True, to='webapp.recompense'),
        ),
    ]
