# Generated by Django 3.2.19 on 2023-05-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20230514_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recompenses',
            field=models.ManyToManyField(blank=True, null=True, to='webapp.recompense'),
        ),
    ]
